import React, { useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import "./backedgaming.scss";
import Heading from "../../heading/heading";
function Backedgaming() {
  gsap.registerPlugin(ScrollTrigger);

  const webRef = useRef(null);
  const istimgRef = useRef(null);
  const secondimgRef = useRef(null);
  const thirdimgRef = useRef(null);
  const forthimgRef = useRef(null);

  useEffect(() => {
    const container = webRef.current;
    const istimg = istimgRef.current;
    const secondimg = secondimgRef.current;
    const thirdimg = thirdimgRef.current;
    const forthimg = forthimgRef.current;

    const mm = gsap.matchMedia();

    mm.add("(min-width: 768px)", () => {
      // Animations for screens wider than 768px
      gsap.set(istimg, { y: "90%", opacity: "0.3" });
      gsap.to(istimg, {
        y: "0%",
        opacity: "1",
        duration: 1,
        scrollTrigger: {
          trigger: container,
          start: "30% 80%",
          toggleActions: "play none none reverse",
        },
      });

      gsap.set(secondimg, { y: "90%", opacity: "0.3" });
      gsap.to(secondimg, {
        y: "0%",
        opacity: "1",
        duration: 1,
        scrollTrigger: {
          trigger: container,
          start: "30% 80%",
          toggleActions: "play none none reverse",
        },
      });

      gsap.set(thirdimg, { y: "90%", opacity: "0.3" });
      gsap.to(thirdimg, {
        y: "0%",
        opacity: "1",
        duration: 1,
        scrollTrigger: {
          trigger: container,
          start: "30% 80%",
          toggleActions: "play none none reverse",
        },
      });

      gsap.set(forthimg, { y: "90%", opacity: "0.3" });
      gsap.to(forthimg, {
        y: "0%",
        opacity: "1",
        duration: 1,
        scrollTrigger: {
          trigger: container,
          start: "30% 80%",
          toggleActions: "play none none reverse",
        },
      });
    });

    return () => {
      mm.revert(); // Clean up the matchMedia
    };
  }, []);
  return (
    <section className="backedgaming-sec" ref={webRef}>
      <Heading
        mainhead={"Bitcion Backed Baming"}
        secondhead={"Bitcion Backed Baming"}
      />
      <div className="inner">
        <div className="top">
          <div className="ist" ref={istimgRef}>
            <img src="/assets/icons/backedgaming/hash.webp" alt="..." />
            <h4 className="text-white textexpansiva-bold fw-bold">
              Exceptional Hashrate
            </h4>
            <p className="text-white text-inter fw-normal">
              Experience unparalleled mining power with the Antminer S21 Hydro,
              designed to maximize your Bitcoin mining potential.
            </p>
          </div>
          <div className="second">
            <img src="/assets/images/backedgaming.webp" alt="" />
          </div>
          <div className="ist" ref={secondimgRef}>
            <img
              src="/assets/icons/backedgaming/optimizeddesign.webp"
              alt="..."
            />
            <h4 className="text-white textexpansiva-bold fw-bold">
              Optimized Design
            </h4>
            <p className="text-white text-inter fw-normal">
              Its design ensures optimal air circulation and cooling, crucial
              for maintaining mining efficiency and hardware longevity.
            </p>
          </div>
        </div>
        <div className="bottom">
          <div className="ist" ref={thirdimgRef}>
            <img src="/assets/icons/backedgaming/cooling.webp" alt="..." />
            <h4 className="text-white textexpansiva-bold fw-bold">
              Advanced Cooling Technology
            </h4>
            <p className="text-white text-inter fw-normal">
              This cutting-edge cooling method not only enhances the miner's
              performance but also significantly reduces its environmental
              impact.
            </p>
          </div>
          <div className="ist" ref={forthimgRef}>
            <img src="/assets/icons/backedgaming/energy.webp" alt="..." />
            <h4 className="text-white textexpansiva-bold fw-bold">
              Green and sustainable energy
            </h4>
            <p className="text-white text-inter fw-normal">
              Electricity generated by gletcher water 100% green and suistanable
            </p>
          </div>
        </div>
      </div>
      <div className="left-back back-div"></div>
      <div className="right-back back-div"></div>
    </section>
  );
}

export default Backedgaming;
