import React from "react";
import "./economycard.scss";
function Economycard() {
  return (
    <section className="economycard-sec">
      <div className="inner">
        <div className="economy-card">
          <div className="ist">
            <div className="left">
              <h4 className="pink textexpansiva-bold fw-bold">
                Decentralized Governance With Burns
              </h4>
              <p className="text-white text-inter fw-normal">
                Players wield governance tokens, allowing them to vote on
                crucial development decisions, game updates, and the overall
                direction of Elements of a Soul. This democratizes game
                development and ensures the community's voice is always heard.
                Unused governance tokens are automatically burned after a
                certain period, reducing supply and increasing the rarity and
                value of the remaining tokens.
              </p>
            </div>
            <div className="right">
              <h4 className="pink textexpansiva-bold fw-bold">
                Staking Rewards
              </h4>
              <p className="text-white text-inter fw-normal">
                By staking NFT plots within the game, players can earn a portion
                of the staking rewards generated by the utility token. This
                mechanism incentivizes long-term engagement and investment in
                the game's ecosystem.
              </p>
            </div>
          </div>
          <div className="ist">
            <div className="left">
              <h4 className="pink textexpansiva-bold fw-bold">
                Utility Token Economy
              </h4>
              <p className="text-white text-inter fw-normal">
                The utility token serves as the backbone of the in-game economy,
                facilitating the purchase of Hashrate tokens, game assets, and
                other essential Items. This creates a vibrant, player-driven
                market.
              </p>
            </div>
            <div className="right">
              <h4 className="pink textexpansiva-bold fw-bold">
                NFT Game Gear with Burning Mechanism
              </h4>
              <p className="text-white text-inter fw-normal">
                All game gear is minted as NFTs with a unique randomized burning
                mechanism when deployed. This Introduces scarcity and value
                appreciation for game items, enhancing the gaming experience.
              </p>
            </div>
          </div>
          <div className="ist">
            <div className="left">
              <h4 className="pink textexpansiva-bold fw-bold">
                Automatic Token Burning Of Battle Hash Token
              </h4>
              <p className="text-white text-inter fw-normal">
                BHT will he burned after a perinde of 3 years, because of the
                lifespan of the mining hardware. BHT can be purchased at any
                time
              </p>
            </div>
            <div className="right">
              <h4 className="pink textexpansiva-bold fw-bold">
                Helper Tokens for Community Engagement
              </h4>
              <p className="text-white text-inter fw-normal">
                Rare Helper Tokens can he earned by assisting other players on
                forums. This fosters supportive and collaborative community,
                rewarding players for their contributions beyond the game.
              </p>
            </div>
          </div>
          <div className="ist">
            <div className="left">
              <h4 className="pink textexpansiva-bold fw-bold">
                Transparent and Fair Asset Distribution
              </h4>
              <p className="text-white text-inter fw-normal">
                The DAD ensures a transparent distribution mechanism for
                rewards, NFTS, and tokens, based on players' participation and
                performance. This promotes fairness and meritocracy within the
                game.
              </p>
            </div>
            <div className="right">
              <h4 className="pink textexpansiva-bold fw-bold">
                Sustainability and Value Retention
              </h4>
              <p className="text-white text-inter fw-normal">
                The burning mechanism for Hashrate tokens after three years
                contributes to the game's sustainability, preventing inflation
                and ensuring long-term value retention for players' assets.
              </p>
            </div>
          </div>
          <div className="ist">
            <div className="left">
              <h4 className="pink textexpansiva-bold fw-bold">
                Vesting and Locking period
              </h4>
              <p className="text-white text-inter fw-normal">
                The vesting and Locking period is the time frame over which
                token holders earn the right to their tokens. This mechanism is
                often used to ensure long-term commitment from team members,
                advisors, and early investors by gradually releasing their token
                allocation over a specified period. Vesting can prevent market
                flooding by restricting the immediate sale of large quantities
                of tokens, thereby supporting a more stable token price
                post-launch.
              </p>
            </div>
            <div className="right">
              <h4 className="pink textexpansiva-bold fw-bold">
                Enhanced Security and Autonomy
              </h4>
              <p className="text-white text-inter fw-normal">
                Running an blockchain technology, the DAO provides enhanced
                security for transactions and player assets, while also granting
                autonomy over the game's evolution and economy
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="left-back back-div"></div>
      <div className="right-back back-div"></div>
    </section>
  );
}

export default Economycard;
